# Generated by Django 3.2.24 on 2024-02-20 17:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0003_device_devicetype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicetype',
            name='name',
            field=models.CharField(max_length=100, unique='True'),
        ),
        migrations.CreateModel(
            name='DeviceModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique='True')),
                ('device_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='devices.devicetype')),
            ],
        ),
    ]
