# Generated by Django 3.2.24 on 2024-02-20 17:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0004_auto_20240220_2041'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='device_model',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='devices.devicemodel'),
            preserve_default=False,
        ),
    ]
