# Generated by Django 3.2.24 on 2024-02-20 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0008_alter_device_device_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicemodel',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
