# Generated by Django 3.2.24 on 2024-02-20 19:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0013_alter_deviceparameter_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='parameters',
        ),
        migrations.AddField(
            model_name='device',
            name='device_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='devices.devicetype'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='DeviceParameter',
        ),
        migrations.DeleteModel(
            name='Parameter',
        ),
    ]
