# Generated by Django 3.2.24 on 2024-02-21 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0014_auto_20240220_2200'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='name',
        ),
    ]
