# Generated by Django 3.2.24 on 2024-02-23 12:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0015_remove_device_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='device_add_time',
            field=models.DateTimeField(default=datetime.datetime.now, editable=False),
        ),
    ]
