# Generated by Django 3.2.24 on 2024-02-23 19:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0017_alter_device_device_add_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('on_the_network', models.BooleanField()),
                ('ip_address', models.GenericIPAddressField()),
                ('serial_number', models.CharField(max_length=20)),
                ('mac_address', models.CharField(max_length=17, validators=[django.core.validators.RegexValidator(regex='^([0-9a-fA-F]{2}[:-]){5}([0-9a-fA-F]{2})$')])),
            ],
        ),
    ]
