# Generated by Django 3.2.24 on 2024-02-24 15:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0020_auto_20240224_1759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parameter',
            name='device',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='devices.device'),
        ),
    ]
