# Generated by Django 3.2.24 on 2024-02-24 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0021_alter_parameter_device'),
    ]

    operations = [
        migrations.AddField(
            model_name='parameter',
            name='device_role',
            field=models.CharField(choices=[('KV', 'Квартальный'), ('SB_KL', 'Субкольцевой'), ('KL', 'Кольцевой'), ('VK', 'Вход в квартал'), ('P_VK', 'Идеальный ВК')], default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='parameter',
            name='port_numbers',
            field=models.IntegerField(choices=[('8', '8'), ('12', '12'), ('24', '24'), ('48', '48')], default=1),
            preserve_default=False,
        ),
    ]
