# Generated by Django 3.2.24 on 2024-02-24 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0022_auto_20240224_1823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parameter',
            name='port_numbers',
            field=models.CharField(choices=[('8', '8'), ('12', '12'), ('24', '24'), ('48', '48')], max_length=4),
        ),
    ]
