# Generated by Django 3.2.24 on 2024-02-24 17:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0023_alter_parameter_port_numbers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='device_type',
        ),
        migrations.RemoveField(
            model_name='parameter',
            name='device_role',
        ),
        migrations.RemoveField(
            model_name='parameter',
            name='ip_address',
        ),
        migrations.RemoveField(
            model_name='parameter',
            name='mac_address',
        ),
        migrations.RemoveField(
            model_name='parameter',
            name='on_the_network',
        ),
        migrations.RemoveField(
            model_name='parameter',
            name='port_numbers',
        ),
        migrations.RemoveField(
            model_name='parameter',
            name='serial_number',
        ),
        migrations.AddField(
            model_name='device',
            name='serial_number',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='parameter',
            name='value',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='parameter',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='devices.device'),
        ),
        migrations.CreateModel(
            name='ParameterField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('data_type', models.CharField(max_length=50)),
                ('device_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='devices.devicetype')),
            ],
        ),
    ]
