# Generated by Django 3.2.24 on 2024-02-24 17:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0025_auto_20240224_2051'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='device_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='devices.devicetype'),
            preserve_default=False,
        ),
    ]
