# Generated by Django 3.2.24 on 2024-02-25 11:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0026_device_device_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parameter',
            name='device',
        ),
        migrations.AddField(
            model_name='parameter',
            name='device_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='devices.devicetype'),
        ),
    ]
