# Generated by Django 3.2.24 on 2024-02-25 11:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0027_auto_20240225_1424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parameter',
            name='device_type',
            field=models.ForeignKey(default=10, on_delete=django.db.models.deletion.CASCADE, to='devices.devicetype'),
            preserve_default=False,
        ),
    ]
