# Generated by Django 3.2.24 on 2024-02-25 12:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0028_alter_parameter_device_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parameter',
            name='device_type',
        ),
        migrations.AddField(
            model_name='parameter',
            name='device',
            field=models.OneToOneField(default=44, on_delete=django.db.models.deletion.CASCADE, to='devices.device'),
            preserve_default=False,
        ),
    ]
