# Generated by Django 3.2.24 on 2024-02-25 13:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0030_auto_20240225_1606'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceTypeParameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('required', models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='devicemodel',
            name='device_type',
        ),
        migrations.RemoveField(
            model_name='devicetype',
            name='available_parameters',
        ),
        migrations.DeleteModel(
            name='Device',
        ),
        migrations.DeleteModel(
            name='DeviceModel',
        ),
        migrations.AddField(
            model_name='devicetypeparameter',
            name='devicetype',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='devices.devicetype'),
        ),
        migrations.AddField(
            model_name='devicetypeparameter',
            name='parameter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='devices.parameter'),
        ),
        migrations.AddField(
            model_name='devicetype',
            name='parameters',
            field=models.ManyToManyField(through='devices.DeviceTypeParameter', to='devices.Parameter'),
        ),
    ]
