# Generated by Django 3.2.24 on 2024-02-25 14:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0032_auto_20240225_1656'),
    ]

    operations = [
        migrations.AddField(
            model_name='parameter',
            name='device',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='devices.device'),
            preserve_default=False,
        ),
    ]
