# Generated by Django 3.2.24 on 2024-02-25 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0033_parameter_device'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicetype',
            name='parameter_settings',
            field=models.CharField(choices=[('1', 'Switch'), ('2', 'Cam'), ('3', 'Wifi')], default=1, max_length=15),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='devicetype',
            name='name',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='parameter',
            name='device_role',
            field=models.CharField(choices=[('KV', 'Квартальный'), ('SUBKL', 'Субкольцевой'), ('KL', 'Кольцевой'), ('VK', 'Вход в квартал'), ('PVK', 'Идеальный ВК')], max_length=20),
        ),
    ]
