# Generated by Django 3.2.24 on 2024-02-25 15:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0035_auto_20240225_1832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parameter',
            name='antenna_height',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='parameter',
            name='azimuth',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='parameter',
            name='cam_number',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='parameter',
            name='device_role',
            field=models.CharField(blank=True, choices=[('KV', 'Квартальный'), ('SUBKL', 'Субкольцевой'), ('KL', 'Кольцевой'), ('VK', 'Вход в квартал'), ('PVK', 'Идеальный ВК')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='parameter',
            name='mac_address',
            field=models.CharField(blank=True, max_length=17, null=True, unique=True, validators=[django.core.validators.RegexValidator(regex='^([0-9a-fA-F]{2}[:-]){5}([0-9a-fA-F]{2})$')]),
        ),
        migrations.AlterField(
            model_name='parameter',
            name='micro',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='parameter',
            name='port_numbers',
            field=models.CharField(blank=True, choices=[('8', '8'), ('12', '12'), ('24', '24'), ('48', '48')], max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='parameter',
            name='serial_number',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='parameter',
            name='view_angle',
            field=models.CharField(blank=True, choices=[('100', '100'), ('90', '90'), ('75', '75'), ('60', '60')], max_length=5, null=True),
        ),
    ]
