# Generated by Django 3.2.24 on 2024-02-25 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0036_auto_20240225_1838'),
    ]

    operations = [
        migrations.AddField(
            model_name='parameter',
            name='comment',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
