# Generated by Django 3.2.24 on 2024-02-25 16:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0037_parameter_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParameterSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_type', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='devices.devicetype')),
                ('fields', models.ManyToManyField(related_name='allowed_for_device_type', to='devices.Parameter')),
            ],
        ),
    ]
